const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const Model = require('../lib/Model.js')
const qml = vm.createContext({})
vm.runInContext(fs.readFileSync(require.resolve('../lib/Model.js'), 'utf8'), qml)
const schedule = times => Model.parseSchedule(JSON.stringify({date: '2026-10-09', prayers: Object.fromEntries(Model.PRAYERS.map((name, i) => [name, {time: times[i]}]))}))
const today = schedule(['05:00', '12:00', '15:00', '18:00', '19:00'])
const tomorrow = schedule(['05:02', '12:01', '15:01', '18:01', '19:01'])
assert.equal(Model.parseSchedule('{'), null)
assert.equal(Model.parseSchedule('{"prayers":{}}'), null)
assert.equal(Model.toMinutes('12:00 AM'), 0)
assert.equal(Model.toMinutes('12:00 PM'), 720)
assert.equal(Model.toMinutes('24:01'), -1)
assert.equal(Model.nextPrayer(today, tomorrow, 300).name, 'dhuhr')
assert.equal(Model.nextPrayer(today, tomorrow, 1140).isTomorrow, true)
assert.equal(Model.nextPrayer(today, tomorrow, 1439).remaining, 303)
assert.equal(Model.nextPrayer(today, null, 1140), null)
assert.equal(Model.nextPrayer(null, tomorrow, 0), null)
assert.equal(Model.prayerState(today.prayers[0], Model.nextPrayer(today, tomorrow, 300), 300), 'past')
assert.equal(Model.barLabel(Model.nextPrayer(today, tomorrow, 1439), true), 'Fajr -05:03')
assert.equal(qml.parseGmt('{"gmt":"UTC-3.5"}'), -210)
assert.equal(qml.parseGmt('{"gmt":"UTC+7.0"}'), 420)
assert.equal(qml.parseGmt('invalid'), null)
const before = new Date('2026-10-09T16:59:00Z')
const after = new Date('2026-10-09T17:00:00Z')
assert.equal(Model.minutesOfDay(before, 420), 1439)
assert.equal(Model.minutesOfDay(after, 420), 0)
assert.equal(qml.dayOf(after, 420) - qml.dayOf(before, 420), 1)
assert.deepEqual(Model.offsetArgs('fajr', '-5'), ['offset', 'fajr', '-5'])
assert.deepEqual(Model.scheduleArgs(1), ['show', '--json', '--day-offset', '1'])
assert.equal(Model.parseConfig('bad'), null)
assert.equal(Model.parseConfig('{"prayers":{"fajr":{"offset":-5}}}').prayers.fajr.offset, -5)
assert.equal(Model.parseConfig('{"location":{"latitude":"wrong"}}').location.latitude, 0)
assert.equal(Model.errorLine('progress\nError: unavailable\nmore'), 'Error: unavailable')
assert.equal(Model.validateLatitude('91') === '', false)
assert.equal(Model.validateOffset('-5'), '')
console.log('ok - parsing, tomorrow transition, location offsets, command offsets, errors and countdown')
